FROM jboss/wildfly
ADD frereth.war /opt/jboss/wildfly/standalone/deployments/

# Note that this already seems to have appropriate
# CMD and ENTRYPOINT settings.

# N.B. This probably needs to be mapped out of VirtualBox,
# if you're using something like docker-machine
EXPOSE 4242
