FROM jboss/wildfly
ADD frereth.war /opt/jboss/wildfly/standalone/deployments/

# Note that this already seems to have appropriate
# CMD and ENTRYPOINT settings.

# TODO: Which port is immutant listening on for the
# nrepl connection?
